openapi: 3.0.0
info:
  title: API Documentation
  version: 1.0.0

securitySchemes:
  BasicAuth:
    type: http
    scheme: basic

tags:
  - name: Blogs
    description: API for managing blogs

paths:
  /api/blogs:
    get:
      summary: Get a list of all blogs
      tags: [Blogs]
      security:
        - BasicAuth: []
      responses:
        200:
          description: List of all blogs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Blog'
    post:
      summary: Add a new blog
      tags: [Blogs]
      security:
        - BasicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BlogInputDto'
      responses:
        201:
          description: The blog was successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blog'
        400:
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'

  /api/blogs/{id}:
    get:
      summary: Get a blog by ID
      tags: [Blogs]
      security:
        - BasicAuth: []
      parameters:
        - in: path
          name: id
          required: true
          description: 'The unique identifier of the blog'
          schema:
            type: string
            example: '123e4567-e89b-12d3-a456-426614174000'
      responses:
        200:
          description: The requested blog
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blog'
        404:
          description: Blog not found
    put:
      summary: Update a blog by ID
      tags: [Blogs]
      security:
        - BasicAuth: []
      parameters:
        - in: path
          name: id
          required: true
          description: 'The unique identifier of the blog'
          schema:
            type: string
            example: '123e4567-e89b-12d3-a456-426614174000'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BlogInputDto'
      responses:
        204:
          description: Blog updated successfully
        400:
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        404:
          description: Blog not found
    delete:
      summary: Delete a blog by ID
      tags: [Blogs]
      security:
        - BasicAuth: []
      parameters:
        - in: path
          name: id
          required: true
          description: 'The unique identifier of the blog'
          schema:
            type: string
            example: '123e4567-e89b-12d3-a456-426614174000'
      responses:
        204:
          description: 'Blog deleted successfully'
        404:
          description: 'Blog not found'

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    Blog:
      type: object
      required:
        - id
        - name
        - description
        - websiteUrl
      properties:
        id:
          type: string
          description: 'The unique identifier for the blog'
          example: '123e4567-e89b-12d3-a456-426614174000'
        name:
          type: string
          description: 'The name of the blog'
          example: 'My First Blog'
        description:
          type: string
          description: 'The description of the blog'
          example: 'This is my first blog about technology'
        websiteUrl:
          type: string
          description: 'The website URL of the blog'
          example: 'https://myblog.com'
    BlogInputDto:
      type: object
      required:
        - name
        - description
        - websiteUrl
      properties:
        name:
          type: string
          description: 'The name of the blog'
          example: 'My First Blog'
        description:
          type: string
          description: 'The description of the blog'
          example: 'This is my first blog about technology'
        websiteUrl:
          type: string
          description: 'The website URL of the blog'
          example: 'https://myblog.com'
    ValidationError:
      type: object
      properties:
        field:
          type: string
          example: 'name'
        message:
          type: string
          example: 'Invalid name'
    ValidationErrorResponse:
      type: object
      properties:
        errorMessages:
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
